name: "Load Testing Action"
description: "Reusable GitHub Action for running load tests with templated k6 scripts."

inputs:
  test_type:
    description: "Type of load test to run (smoke, acceptance, stress, soak)"
    required: true

  scenario_path:
    description: "Path to scenario file in the calling repository"
    required: true
  
  dependencies_file_path:
    description: "Path the dependencies of the repo"
    required: false
    default: ""
  
  variables:
    required: false
    description: "JSON object containing env variables for scenarios"
    default: "{}"

  email_notify:
    description: "Enable email summary notification (true/false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout caller repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: caller_repo
    
    - name: Checkout this action
      uses: actions/checkout@v4
      with:
        repository: myriad-actions/load-test-actions
        path: action_repo
    
    - name: Validate scenario file and its executable
      shell: bash
      id: validation_step
      run: |
        if [ ! -f "caller_repo/${{ inputs.scenario_path }}" ]; then
          echo "Scenario file not found: caller_repo/${{ inputs.scenario_path }}"
          exit 1
        fi
        cp caller_repo/${{ inputs.scenario_path }} action_repo/scenario.js

        DEP_PATH="caller_repo/${{ inputs.dependencies_file_path }}"
        if [ ! -f "$DEP_PATH" ]; then
          echo "WARNING: Dependencies file not found at: $DEP_PATH"
          ISSUE_BODY="Please approve this ${{ inputs.test_type }} load test. No dependencies file provided."
          echo "ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_OUTPUT
        else
          # Read and clean the content - remove comment lines starting with #
          DEPS_CONTENT=$(grep -v '^#' "$DEP_PATH" | head -20 | tr '\n' ' ')
          ISSUE_BODY="Please approve this ${{ inputs.test_type }} load test. Dependencies: $DEPS_CONTENT"
          echo "ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_OUTPUT
        fi
    
    - name: Require Manual DevOps approval for heavy tests
      if: ${{ inputs.test_type == 'stress' || inputs.test_type == 'soak' }}
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: Myriad-Sira
        minimum-approvals: 1
        issue-title: "Manual Approval Required for heavy load tests."
        issue-body: ${{ steps.validation_step.outputs.ISSUE_BODY }}
    
    - name: Install jq
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Parse variables into env file
      shell: bash
      run: |
        echo '${{ inputs.variables }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .envvars
        cat .envvars
    
    - name: Load variables into environment
      shell: bash
      run: |
        export $(cat .envvars | xargs)
    
    - name: Setup k6
      uses: grafana/setup-k6-action@v1

    - name: Run Load Test
      shell: bash
      working-directory: ./action_repo
      run: |
        k6 run \
          templates/${{ inputs.test_type }}.js

    - name: Send Email Notification
      if: ${{ inputs.email_notify == 'true' }}
      shell: bash
      run: |
        echo "TODO: Repo is public and send mail required secret configs"