name: "Load Testing Action"
description: "Reusable GitHub Action for running load tests with dynamic k6 scenarios + Prometheus metrics"

inputs:
  test_type:
    description: "Type of load test to run (smoke, acceptance, stress, soak)"
    required: true

  config_path:
    description: "Path to config file with scenarios, SLAs, etc (e.g. load_test/config.js)"
    required: true
  
  dependencies_file_path:
    description: "Path to dependencies file"
    required: false
    default: ""
  
  variables:
    required: false
    description: "JSON object containing env variables for scenarios"
    default: "{}"

  email_notify:
    description: "Enable email summary notification (true/false)"
    required: false
    default: "false"

outputs:
  test_passed:
    description: "Did the load test pass?"
    value: ${{ steps.run-test.outputs.test_passed }}
  report_path:
    description: "Path to unified JSON report"
    value: ${{ steps.merge-reports.outputs.report_path }}
  cpu_max:
    description: "Max CPU usage during test"
    value: ${{ steps.prometheus-step.outputs.cpu_max }}
  mem_max:
    description: "Max memory usage during test"
    value: ${{ steps.prometheus-step.outputs.mem_max }}

runs:
  using: "composite"
  steps:
    - name: Checkout caller repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: caller_repo
    
    - name: Checkout this action
      uses: actions/checkout@v4
      with:
        repository: myriad-actions/load-test-actions
        ref: ${{ github.ref_name }}
        path: action_repo
    
    - name: Validate config file
      id: validation_step
      shell: bash
      run: |
        CONFIG_PATH="caller_repo/${{ inputs.config_path }}"
        if [ ! -f "$CONFIG_PATH" ]; then
          echo "Load Test Config file not found: $CONFIG_PATH"
          exit 1
        fi
        cp "$CONFIG_PATH" action_repo/config.js
        echo "Config copied: action_repo/config.js"

        DEP_PATH="caller_repo/${{ inputs.dependencies_file_path }}"
        if [ ! -f "$DEP_PATH" ]; then
          echo "âš ï¸ Dependencies file not found: $DEP_PATH"
          ISSUE_BODY="Please approve this ${{ inputs.test_type }} load test. No dependencies provided."
          echo "ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_OUTPUT
        else
          DEPS_CONTENT=$(grep -v '^#' "$DEP_PATH" | head -20 | tr '\n' ' ')
          ISSUE_BODY="Please approve ${{ inputs.test_type }} load test. Dependencies: $DEPS_CONTENT"
          echo "ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_OUTPUT
        fi
    
    - name: Require Manual Approval (stress/soak)
      if: ${{ inputs.test_type == 'stress' || inputs.test_type == 'soak' }}
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: Myriad-Sira
        minimum-approvals: 1
        issue-title: "Manual Approval: ${{ inputs.test_type }} Load Test"
        issue-body: ${{ steps.validation_step.outputs.ISSUE_BODY }}
    
    - name: Install jq
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y jq
    
    - name: Parse variables to .env
      shell: bash
      run: |
        echo '${{ inputs.variables }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .envvars
        cat .envvars
    
    - name: Load environment variables
      shell: bash
      run: |
        export $(cat .envvars | xargs)
    
    - name: Setup k6
      uses: grafana/setup-k6-action@v1
    
    - name: Start Load Test Timer
      id: start-timer
      shell: bash
      run: |
        START_TIME=$(date +%s)
        echo "start_time=$START_TIME" >> $GITHUB_OUTPUT
        echo "START_TIME=$START_TIME" >> $GITHUB_ENV
        echo "ðŸŸ¢ Test START: $(date -d "@$START_TIME")"
    
    - name: Run Load Test
      id: run-test
      shell: bash
      working-directory: ./action_repo
      continue-on-error: true
      env:
        TEST_TYPE: ${{ inputs.test_type }}
        SCENARIO_FILE: config.js  # From caller_repo
        START_TIME: ${{ steps.start-timer.outputs.start_time }}
      run: |
        k6 run \
          --out json=results.json \
          --summary-export=summary-${{ inputs.test_type }}.json \
          entrypoint.js
    
    - name: End Load Test Timer
      id: end-timer
      shell: bash
      run: |
        END_TIME=$(date +%s)
        echo "end_time=$END_TIME" >> $GITHUB_OUTPUT
        echo "END_TIME=$END_TIME" >> $GITHUB_ENV
        echo "ðŸŸ¢ Test EDN: $(date -d "@$END_TIME")"
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install deps
      shell: bash
      working-directory: ./action_repo
      run: npm init -y && npm install node-fetch@3
    
    - name: Collect Prometheus Metrics
      id: prometheus-step
      if: always()
      shell: bash
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
        TEST_START_TIMESTAMP: ${{ steps.start-timer.outputs.start_time }}
        TEST_END_TIMESTAMP: ${{ steps.end-timer.outputs.end_time }}
      working-directory: ./action_repo
      run: |
        node prometheus-metrics.js > prometheus-metrics.json
        cat prometheus-metrics.json
    
    - name: Merge Load Test + Prometheus Reports
      id: merge-reports
      if: always()
      working-directory: ./action_repo
      shell: bash
      run: |
        ls -la *.json || echo "No JSON files found"

        # Create fallback files
        SUMMARY_FILE="summary-${{ inputs.test_type }}.json"
        PROM_FILE="prometheus-metrics.json"
        
        [ -f "$SUMMARY_FILE" ] || echo '{}' > "$SUMMARY_FILE"
        [ -f "$PROM_FILE" ] || echo '{}' > "$PROM_FILE"

        # Validate JSON
        K6_JSON=$(cat "$SUMMARY_FILE" | jq . 2>/dev/null || echo '{}')
        PROM_JSON=$(cat "$PROM_FILE" | jq . 2>/dev/null || echo '{}')

        cat > unified-report.json << EOF
        {
          "load_test": ${K6_JSON},
          "prometheus": ${PROM_JSON},
          "repository": "${{ github.event.repository.name }}",
          "test_type": "${{ inputs.test_type }}"
        }
        EOF
        
        echo "âœ… Unified report created"
        cat unified-report.json
        echo "report_path=unified-report.json" >> $GITHUB_OUTPUT

    # - name: Send Email Notification
    #   if: ${{ inputs.email_notify == 'true' }}
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     server_address: smtp.gmail.com
    #     server_port: 587
    #     username: ${{ secrets.EMAIL_USERNAME }}
    #     password: ${{ secrets.EMAIL_PASSWORD }}
    #     subject: "ðŸ§ª Load Test: ${{ inputs.test_type }} - ${{ steps.run-test.outputs.test_passed }}"
    #     to: devops@company.com
    #     from: load-test@company.com
    #     html_body_file: load-test-report.html
    #     secure: true
